
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS ARREGLO ARREGLO_BI LPAREN RPAREN NUMBERS OPERADOR BOOLEAN POINT COMA RCORCHER LCORCHER DOUBLEPOINT ID AS FROM ZEROS RESHAPE IMPORT ARRAY NUMPY SHAPE SIZEexpression : IMPORT NUMPY AS ID\n                      | IMPORT ID FROM ID\n                       '
    
_lr_action_items = {'FROM':([4,],[6,]),'AS':([3,],[5,]),'IMPORT':([0,],[1,]),'NUMPY':([1,],[3,]),'ID':([1,5,6,],[4,7,8,]),'$end':([2,7,8,],[0,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> IMPORT NUMPY AS ID','expression',4,'p_expresion_import','programaCompleto.py',72),
  ('expression -> IMPORT ID FROM ID','expression',4,'p_expresion_import','programaCompleto.py',73),
]
