
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '6F705DA847C4C2E08F7D089753CAA1EE'
    
_lr_action_items = {'EQUALS':([1,],[3,]),'$end':([2,11,14,16,18,20,21,23,24,],[0,-1,-2,-5,-3,-6,-4,-7,-8,]),'NUMBERS':([4,7,8,12,13,19,],[6,9,10,15,17,22,]),'RCORCHER':([8,10,12,13,15,17,19,22,],[11,14,16,18,20,21,23,24,]),'ID':([0,3,],[1,5,]),'LCORCHER':([1,5,],[4,7,]),'DOUBLEPOINT':([6,9,10,15,],[8,12,13,19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> ID LCORCHER NUMBERS DOUBLEPOINT RCORCHER','expression',5,'p_expression_slicing','programaCompleto.py',532),
  ('expression -> ID LCORCHER NUMBERS DOUBLEPOINT NUMBERS RCORCHER','expression',6,'p_expression_slicing','programaCompleto.py',533),
  ('expression -> ID LCORCHER NUMBERS DOUBLEPOINT NUMBERS DOUBLEPOINT RCORCHER','expression',7,'p_expression_slicing','programaCompleto.py',534),
  ('expression -> ID LCORCHER NUMBERS DOUBLEPOINT NUMBERS DOUBLEPOINT NUMBERS RCORCHER','expression',8,'p_expression_slicing','programaCompleto.py',535),
  ('expression -> ID EQUALS ID LCORCHER NUMBERS DOUBLEPOINT RCORCHER','expression',7,'p_expression_slicing','programaCompleto.py',536),
  ('expression -> ID EQUALS ID LCORCHER NUMBERS DOUBLEPOINT NUMBERS RCORCHER','expression',8,'p_expression_slicing','programaCompleto.py',537),
  ('expression -> ID EQUALS ID LCORCHER NUMBERS DOUBLEPOINT NUMBERS DOUBLEPOINT RCORCHER','expression',9,'p_expression_slicing','programaCompleto.py',538),
  ('expression -> ID EQUALS ID LCORCHER NUMBERS DOUBLEPOINT NUMBERS DOUBLEPOINT NUMBERS RCORCHER','expression',10,'p_expression_slicing','programaCompleto.py',539),
]
