
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSNAME NUMBER PLUS MINUS TIMES DIVIDE EQUALS LPAREN RPARENstatement : NAME EQUALS expressionstatement : expressionexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : MINUS expression %prec UMINUSexpression : LPAREN expression RPARENexpression : NUMBERexpression : NAME'
    
_lr_action_items = {'$end':([2,3,4,5,7,8,15,16,17,18,19,20,],[0,-9,-10,-2,-7,-10,-1,-6,-4,-3,-5,-8,]),'EQUALS':([4,],[9,]),'MINUS':([0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[1,1,-9,-10,11,1,-7,-10,1,1,1,1,1,11,11,-6,-4,-3,-5,-8,]),'NUMBER':([0,1,6,9,10,11,12,13,],[3,3,3,3,3,3,3,3,]),'NAME':([0,1,6,9,10,11,12,13,],[4,8,8,8,8,8,8,8,]),'DIVIDE':([3,4,5,7,8,14,15,16,17,18,19,20,],[-9,-10,10,-7,-10,10,10,-6,10,10,-5,-8,]),'RPAREN':([3,7,8,14,16,17,18,19,20,],[-9,-7,-10,20,-6,-4,-3,-5,-8,]),'LPAREN':([0,1,6,9,10,11,12,13,],[6,6,6,6,6,6,6,6,]),'PLUS':([3,4,5,7,8,14,15,16,17,18,19,20,],[-9,-10,12,-7,-10,12,12,-6,-4,-3,-5,-8,]),'TIMES':([3,4,5,7,8,14,15,16,17,18,19,20,],[-9,-10,13,-7,-10,13,13,-6,13,13,-5,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,1,6,9,10,11,12,13,],[5,7,14,15,16,17,18,19,]),'statement':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','calculadora.py',62),
  ('statement -> expression','statement',1,'p_statement_expr','calculadora.py',67),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','calculadora.py',72),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','calculadora.py',73),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','calculadora.py',74),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','calculadora.py',75),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','calculadora.py',87),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','calculadora.py',92),
  ('expression -> NUMBER','expression',1,'p_expression_number','calculadora.py',97),
  ('expression -> NAME','expression',1,'p_expression_name','calculadora.py',102),
]
