
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID IMPORT AS NUMPY FROMexpression : IMPORT NUMPY AS ID\n                      | IMPORT ID FROM ID\n                      '
    
_lr_action_items = {'IMPORT':([0,],[2,]),'$end':([1,7,8,],[0,-1,-2,]),'NUMPY':([2,],[3,]),'ID':([2,5,6,],[4,7,8,]),'AS':([3,],[5,]),'FROM':([4,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> IMPORT NUMPY AS ID','expression',4,'p_expresion_import','programa.py',51),
  ('expression -> IMPORT ID FROM ID','expression',4,'p_expresion_import','programa.py',52),
]
