
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '9A44BCF08B268AB20027AF0548474309'
    
_lr_action_items = {'EQUALS':([1,],[3,]),'ARRAY':([5,],[6,]),'ID':([0,3,],[1,4,]),'RPAREN':([8,],[9,]),'ARREGLO':([7,],[8,]),'$end':([2,9,],[0,-1,]),'LPAREN':([6,],[7,]),'POINT':([4,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> ID EQUALS ID POINT ARRAY LPAREN ARREGLO RPAREN','expression',8,'p_expresion_arreglo','experimento.py',151),
]
