
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '4515E47EC8583416A9FCE077992E1602'
    
_lr_action_items = {'COMA':([14,29,30,31,53,54,65,67,77,80,98,],[28,52,-56,55,-54,-55,92,94,-53,105,121,]),'RPAREN':([43,44,63,64,67,68,69,82,83,85,86,93,95,100,101,103,104,106,107,109,110,111,112,114,115,119,120,122,123,125,126,127,128,130,131,132,141,],[66,68,90,91,95,96,97,108,109,113,114,-23,-21,124,125,129,130,133,134,135,136,137,138,139,140,-24,-22,142,143,144,145,146,147,148,149,150,151,]),'LCORCHER':([2,20,25,58,59,71,72,],[14,42,14,81,84,99,102,]),'ZEROS':([16,21,],[34,45,]),'VAR':([0,13,15,17,],[2,25,33,25,]),'NP':([0,13,17,],[3,3,3,]),'POINT':([3,10,],[16,21,]),'RCORCHER':([29,30,32,42,50,51,52,53,54,55,65,75,76,77,78,79,81,84,99,102,],[-58,-56,56,64,-63,-60,-59,-54,-55,-62,93,-64,-57,-53,-61,-65,107,112,123,128,]),'ARREGLO':([20,42,44,58,59,71,72,81,83,84,86,92,94,99,101,102,104,],[43,65,67,82,85,100,103,65,67,65,67,65,67,65,67,65,67,]),'ARRAY':([16,21,41,],[36,47,62,]),'ID':([0,7,12,40,41,48,49,87,88,89,],[5,18,23,60,61,73,74,116,117,118,]),'DOUBLEPOINT':([14,28,29,51,52,55,76,79,],[30,30,53,53,30,30,53,53,]),'FROM':([0,],[7,]),'OPERADOR':([2,25,],[15,15,]),'EQUALS':([2,5,],[13,17,]),'LPAREN':([9,20,34,35,36,45,46,47,58,59,71,72,],[20,44,57,58,59,70,71,72,83,86,101,104,]),'$end':([1,4,6,8,11,22,23,24,26,27,33,37,38,39,56,60,61,62,66,73,74,90,91,96,97,108,113,116,117,118,124,129,133,134,135,136,137,138,139,140,142,143,144,145,146,147,148,149,150,151,],[-8,-4,-7,0,-1,-12,-18,-10,-6,-3,-52,-9,-5,-2,-66,-19,-15,-13,-50,-11,-17,-47,-48,-49,-46,-34,-29,-20,-16,-14,-45,-40,-31,-32,-33,-30,-26,-27,-28,-25,-42,-43,-44,-41,-37,-38,-39,-36,-35,-51,]),'FUNCION':([0,13,16,17,21,],[9,9,35,9,46,]),'NUMBERS':([14,28,30,52,53,55,57,70,105,121,],[29,51,54,76,77,79,80,98,132,141,]),'NUMPY':([0,7,12,13,17,],[10,19,22,10,10,]),'IMPORT':([0,18,19,],[12,40,41,]),'AS':([22,23,60,61,62,],[48,49,87,88,89,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'variosarreglos2':([42,81,84,92,99,102,],[63,106,111,119,122,127,]),'slicer':([14,28,52,55,],[31,50,75,78,]),'importacion':([0,],[6,]),'indexacion':([0,13,17,],[1,24,37,]),'variosarreglos':([44,83,86,94,101,104,],[69,110,115,120,126,131,]),'operacion':([0,13,17,],[4,26,38,]),'arreglo':([0,13,17,],[11,27,39,]),'indice':([14,],[32,]),'statement':([0,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> arreglo','statement',1,'p_statement','compilador numpy.py',71),
  ('statement -> ID EQUALS arreglo','statement',3,'p_statement','compilador numpy.py',72),
  ('statement -> VAR EQUALS arreglo','statement',3,'p_statement','compilador numpy.py',73),
  ('statement -> operacion','statement',1,'p_statement','compilador numpy.py',74),
  ('statement -> ID EQUALS operacion','statement',3,'p_statement','compilador numpy.py',75),
  ('statement -> VAR EQUALS operacion','statement',3,'p_statement','compilador numpy.py',76),
  ('statement -> importacion','statement',1,'p_statement','compilador numpy.py',77),
  ('statement -> indexacion','statement',1,'p_statement','compilador numpy.py',78),
  ('statement -> ID EQUALS indexacion','statement',3,'p_statement','compilador numpy.py',79),
  ('statement -> VAR EQUALS indexacion','statement',3,'p_statement','compilador numpy.py',80),
  ('importacion -> IMPORT NUMPY AS ID','importacion',4,'p_importacion','compilador numpy.py',97),
  ('importacion -> IMPORT NUMPY','importacion',2,'p_importacion','compilador numpy.py',98),
  ('importacion -> FROM NUMPY IMPORT ARRAY','importacion',4,'p_importacion','compilador numpy.py',99),
  ('importacion -> FROM NUMPY IMPORT ARRAY AS ID','importacion',6,'p_importacion','compilador numpy.py',100),
  ('importacion -> FROM NUMPY IMPORT ID','importacion',4,'p_importacion','compilador numpy.py',101),
  ('importacion -> FROM NUMPY IMPORT ID AS ID','importacion',6,'p_importacion','compilador numpy.py',102),
  ('importacion -> IMPORT ID AS ID','importacion',4,'p_importacion','compilador numpy.py',103),
  ('importacion -> IMPORT ID','importacion',2,'p_importacion','compilador numpy.py',104),
  ('importacion -> FROM ID IMPORT ID','importacion',4,'p_importacion','compilador numpy.py',105),
  ('importacion -> FROM ID IMPORT ID AS ID','importacion',6,'p_importacion','compilador numpy.py',106),
  ('variosarreglos -> ARREGLO RPAREN','variosarreglos',2,'p_variosarreglos','compilador numpy.py',153),
  ('variosarreglos -> ARREGLO COMA variosarreglos','variosarreglos',3,'p_variosarreglos','compilador numpy.py',154),
  ('variosarreglos2 -> ARREGLO RCORCHER','variosarreglos2',2,'p_variosarreglos2','compilador numpy.py',173),
  ('variosarreglos2 -> ARREGLO COMA variosarreglos2','variosarreglos2',3,'p_variosarreglos2','compilador numpy.py',174),
  ('arreglo -> NP POINT ARRAY LPAREN LPAREN variosarreglos RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',192),
  ('arreglo -> NP POINT ARRAY LPAREN LCORCHER variosarreglos2 RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',193),
  ('arreglo -> NP POINT ARRAY LPAREN LCORCHER RCORCHER RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',194),
  ('arreglo -> NP POINT ARRAY LPAREN LPAREN RPAREN RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',195),
  ('arreglo -> NP POINT ARRAY LPAREN ARREGLO RPAREN','arreglo',6,'p_arreglo','compilador numpy.py',196),
  ('arreglo -> NP POINT FUNCION LPAREN LPAREN variosarreglos RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',197),
  ('arreglo -> NP POINT FUNCION LPAREN LCORCHER variosarreglos2 RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',198),
  ('arreglo -> NP POINT FUNCION LPAREN LCORCHER RCORCHER RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',199),
  ('arreglo -> NP POINT FUNCION LPAREN LPAREN RPAREN RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',200),
  ('arreglo -> NP POINT FUNCION LPAREN ARREGLO RPAREN','arreglo',6,'p_arreglo','compilador numpy.py',201),
  ('arreglo -> NP POINT ZEROS LPAREN NUMBERS COMA NUMBERS RPAREN','arreglo',8,'p_arreglo','compilador numpy.py',202),
  ('arreglo -> NUMPY POINT ARRAY LPAREN LPAREN variosarreglos RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',203),
  ('arreglo -> NUMPY POINT ARRAY LPAREN LCORCHER variosarreglos2 RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',204),
  ('arreglo -> NUMPY POINT ARRAY LPAREN LCORCHER RCORCHER RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',205),
  ('arreglo -> NUMPY POINT ARRAY LPAREN LPAREN RPAREN RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',206),
  ('arreglo -> NUMPY POINT ARRAY LPAREN ARREGLO RPAREN','arreglo',6,'p_arreglo','compilador numpy.py',207),
  ('arreglo -> NUMPY POINT FUNCION LPAREN LPAREN variosarreglos RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',208),
  ('arreglo -> NUMPY POINT FUNCION LPAREN LCORCHER variosarreglos2 RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',209),
  ('arreglo -> NUMPY POINT FUNCION LPAREN LCORCHER RCORCHER RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',210),
  ('arreglo -> NUMPY POINT FUNCION LPAREN LPAREN RPAREN RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',211),
  ('arreglo -> NUMPY POINT FUNCION LPAREN ARREGLO RPAREN','arreglo',6,'p_arreglo','compilador numpy.py',212),
  ('arreglo -> FUNCION LPAREN LPAREN variosarreglos RPAREN','arreglo',5,'p_arreglo','compilador numpy.py',213),
  ('arreglo -> FUNCION LPAREN LCORCHER variosarreglos2 RPAREN','arreglo',5,'p_arreglo','compilador numpy.py',214),
  ('arreglo -> FUNCION LPAREN LCORCHER RCORCHER RPAREN','arreglo',5,'p_arreglo','compilador numpy.py',215),
  ('arreglo -> FUNCION LPAREN LPAREN RPAREN RPAREN','arreglo',5,'p_arreglo','compilador numpy.py',216),
  ('arreglo -> FUNCION LPAREN ARREGLO RPAREN','arreglo',4,'p_arreglo','compilador numpy.py',217),
  ('arreglo -> NUMPY POINT ZEROS LPAREN NUMBERS COMA NUMBERS RPAREN','arreglo',8,'p_arreglo','compilador numpy.py',218),
  ('operacion -> VAR OPERADOR VAR','operacion',3,'p_operacion','compilador numpy.py',235),
  ('slicer -> NUMBERS DOUBLEPOINT NUMBERS','slicer',3,'p_slicer','compilador numpy.py',258),
  ('slicer -> NUMBERS DOUBLEPOINT','slicer',2,'p_slicer','compilador numpy.py',259),
  ('slicer -> DOUBLEPOINT NUMBERS','slicer',2,'p_slicer','compilador numpy.py',260),
  ('slicer -> DOUBLEPOINT','slicer',1,'p_slicer','compilador numpy.py',261),
  ('indice -> NUMBERS COMA NUMBERS','indice',3,'p_indice','compilador numpy.py',272),
  ('indice -> NUMBERS','indice',1,'p_indice','compilador numpy.py',273),
  ('indice -> NUMBERS COMA','indice',2,'p_indice','compilador numpy.py',274),
  ('indice -> COMA NUMBERS','indice',2,'p_indice','compilador numpy.py',275),
  ('indice -> slicer COMA slicer','indice',3,'p_indice','compilador numpy.py',276),
  ('indice -> slicer COMA','indice',2,'p_indice','compilador numpy.py',277),
  ('indice -> COMA slicer','indice',2,'p_indice','compilador numpy.py',278),
  ('indice -> NUMBERS COMA slicer','indice',3,'p_indice','compilador numpy.py',279),
  ('indice -> slicer COMA NUMBERS','indice',3,'p_indice','compilador numpy.py',280),
  ('indexacion -> VAR LCORCHER indice RCORCHER','indexacion',4,'p_indexacion','compilador numpy.py',290),
]
