
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'E4D0376B4479E1B44967BBFB3D9A801D'
    
_lr_action_items = {'ID':([0,4,11,31,32,48,49,102,103,104,],[1,15,22,53,54,72,73,129,130,131,]),'OPERADOR':([5,25,],[17,17,]),'RCORCHER':([34,35,36,44,55,56,57,59,60,61,68,78,80,82,83,84,85,86,98,99,],[-58,-56,58,67,-54,-59,-55,-60,-63,-62,93,109,112,-53,-57,-64,-65,-61,122,124,]),'VAR':([0,13,17,19,],[5,25,33,25,]),'NUMPY':([0,4,11,13,19,],[3,16,23,3,3,]),'AS':([15,16,72,73,74,],[31,32,102,103,104,]),'IMPORT':([0,22,23,],[4,48,49,]),'ZEROS':([14,21,],[28,45,]),'POINT':([3,8,],[14,21,]),'$end':([2,6,9,10,12,15,16,24,26,27,33,39,40,41,53,54,58,62,72,73,74,89,90,91,92,106,111,119,126,129,130,131,133,134,135,136,137,138,139,140,142,143,144,145,146,147,148,149,150,151,],[-1,-7,-4,0,-8,-18,-12,-2,-5,-9,-52,-3,-6,-10,-17,-11,-66,-50,-19,-15,-13,-46,-49,-47,-48,-40,-45,-29,-34,-20,-16,-14,-39,-36,-38,-37,-43,-42,-44,-41,-28,-25,-27,-26,-32,-31,-33,-30,-51,-35,]),'NUMBERS':([18,35,37,50,55,56,61,69,105,118,],[34,57,59,75,82,83,85,95,132,141,]),'ARREGLO':([20,43,44,51,52,70,71,77,78,80,81,88,94,97,98,99,101,],[42,63,68,76,79,96,100,63,68,68,63,63,68,63,68,68,63,]),'NP':([0,13,19,],[8,8,8,]),'FUNCION':([0,13,14,19,21,],[7,7,30,7,47,]),'RPAREN':([42,43,63,64,65,66,67,76,77,79,81,87,93,96,97,100,101,107,108,109,110,112,113,114,115,116,117,120,121,122,123,124,125,127,128,132,141,],[62,65,87,89,90,91,92,106,107,111,114,-21,-23,119,120,126,127,133,134,135,136,137,138,139,140,-22,-24,142,143,144,145,146,147,148,149,150,151,]),'DOUBLEPOINT':([18,34,37,56,59,61,83,85,],[35,55,35,35,55,35,55,55,]),'COMA':([18,34,35,38,55,57,63,68,75,82,95,],[37,56,-56,61,-54,-55,88,94,105,-53,118,]),'LCORCHER':([5,20,25,51,52,70,71,],[18,44,18,78,80,98,99,]),'FROM':([0,],[11,]),'ARRAY':([14,21,49,],[29,46,74,]),'LPAREN':([7,20,28,29,30,45,46,47,51,52,70,71,],[20,43,50,51,52,69,70,71,77,81,97,101,]),'EQUALS':([1,5,],[13,19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'arreglo':([0,13,19,],[2,24,39,]),'indice':([18,],[36,]),'variosarreglos':([43,77,81,88,97,101,],[64,108,115,116,121,128,]),'slicer':([18,37,56,61,],[38,60,84,86,]),'variosarreglos2':([44,78,80,94,98,99,],[66,110,113,117,123,125,]),'operacion':([0,13,19,],[9,26,40,]),'importacion':([0,],[6,]),'statement':([0,],[10,]),'indexacion':([0,13,19,],[12,27,41,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> arreglo','statement',1,'p_statement','compilador numpy.py',71),
  ('statement -> ID EQUALS arreglo','statement',3,'p_statement','compilador numpy.py',72),
  ('statement -> VAR EQUALS arreglo','statement',3,'p_statement','compilador numpy.py',73),
  ('statement -> operacion','statement',1,'p_statement','compilador numpy.py',74),
  ('statement -> ID EQUALS operacion','statement',3,'p_statement','compilador numpy.py',75),
  ('statement -> VAR EQUALS operacion','statement',3,'p_statement','compilador numpy.py',76),
  ('statement -> importacion','statement',1,'p_statement','compilador numpy.py',77),
  ('statement -> indexacion','statement',1,'p_statement','compilador numpy.py',78),
  ('statement -> ID EQUALS indexacion','statement',3,'p_statement','compilador numpy.py',79),
  ('statement -> VAR EQUALS indexacion','statement',3,'p_statement','compilador numpy.py',80),
  ('importacion -> IMPORT NUMPY AS ID','importacion',4,'p_importacion','compilador numpy.py',97),
  ('importacion -> IMPORT NUMPY','importacion',2,'p_importacion','compilador numpy.py',98),
  ('importacion -> FROM NUMPY IMPORT ARRAY','importacion',4,'p_importacion','compilador numpy.py',99),
  ('importacion -> FROM NUMPY IMPORT ARRAY AS ID','importacion',6,'p_importacion','compilador numpy.py',100),
  ('importacion -> FROM NUMPY IMPORT ID','importacion',4,'p_importacion','compilador numpy.py',101),
  ('importacion -> FROM NUMPY IMPORT ID AS ID','importacion',6,'p_importacion','compilador numpy.py',102),
  ('importacion -> IMPORT ID AS ID','importacion',4,'p_importacion','compilador numpy.py',103),
  ('importacion -> IMPORT ID','importacion',2,'p_importacion','compilador numpy.py',104),
  ('importacion -> FROM ID IMPORT ID','importacion',4,'p_importacion','compilador numpy.py',105),
  ('importacion -> FROM ID IMPORT ID AS ID','importacion',6,'p_importacion','compilador numpy.py',106),
  ('variosarreglos -> ARREGLO RPAREN','variosarreglos',2,'p_variosarreglos','compilador numpy.py',153),
  ('variosarreglos -> ARREGLO COMA variosarreglos','variosarreglos',3,'p_variosarreglos','compilador numpy.py',154),
  ('variosarreglos2 -> ARREGLO RCORCHER','variosarreglos2',2,'p_variosarreglos2','compilador numpy.py',173),
  ('variosarreglos2 -> ARREGLO COMA variosarreglos2','variosarreglos2',3,'p_variosarreglos2','compilador numpy.py',174),
  ('arreglo -> NP POINT ARRAY LPAREN LPAREN variosarreglos RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',192),
  ('arreglo -> NP POINT ARRAY LPAREN LCORCHER variosarreglos2 RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',193),
  ('arreglo -> NP POINT ARRAY LPAREN LCORCHER RCORCHER RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',194),
  ('arreglo -> NP POINT ARRAY LPAREN LPAREN RPAREN RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',195),
  ('arreglo -> NP POINT ARRAY LPAREN ARREGLO RPAREN','arreglo',6,'p_arreglo','compilador numpy.py',196),
  ('arreglo -> NP POINT FUNCION LPAREN LPAREN variosarreglos RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',197),
  ('arreglo -> NP POINT FUNCION LPAREN LCORCHER variosarreglos2 RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',198),
  ('arreglo -> NP POINT FUNCION LPAREN LCORCHER RCORCHER RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',199),
  ('arreglo -> NP POINT FUNCION LPAREN LPAREN RPAREN RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',200),
  ('arreglo -> NP POINT FUNCION LPAREN ARREGLO RPAREN','arreglo',6,'p_arreglo','compilador numpy.py',201),
  ('arreglo -> NP POINT ZEROS LPAREN NUMBERS COMA NUMBERS RPAREN','arreglo',8,'p_arreglo','compilador numpy.py',202),
  ('arreglo -> NUMPY POINT ARRAY LPAREN LPAREN variosarreglos RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',203),
  ('arreglo -> NUMPY POINT ARRAY LPAREN LCORCHER variosarreglos2 RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',204),
  ('arreglo -> NUMPY POINT ARRAY LPAREN LCORCHER RCORCHER RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',205),
  ('arreglo -> NUMPY POINT ARRAY LPAREN LPAREN RPAREN RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',206),
  ('arreglo -> NUMPY POINT ARRAY LPAREN ARREGLO RPAREN','arreglo',6,'p_arreglo','compilador numpy.py',207),
  ('arreglo -> NUMPY POINT FUNCION LPAREN LPAREN variosarreglos RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',208),
  ('arreglo -> NUMPY POINT FUNCION LPAREN LCORCHER variosarreglos2 RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',209),
  ('arreglo -> NUMPY POINT FUNCION LPAREN LCORCHER RCORCHER RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',210),
  ('arreglo -> NUMPY POINT FUNCION LPAREN LPAREN RPAREN RPAREN','arreglo',7,'p_arreglo','compilador numpy.py',211),
  ('arreglo -> NUMPY POINT FUNCION LPAREN ARREGLO RPAREN','arreglo',6,'p_arreglo','compilador numpy.py',212),
  ('arreglo -> FUNCION LPAREN LPAREN variosarreglos RPAREN','arreglo',5,'p_arreglo','compilador numpy.py',213),
  ('arreglo -> FUNCION LPAREN LCORCHER variosarreglos2 RPAREN','arreglo',5,'p_arreglo','compilador numpy.py',214),
  ('arreglo -> FUNCION LPAREN LCORCHER RCORCHER RPAREN','arreglo',5,'p_arreglo','compilador numpy.py',215),
  ('arreglo -> FUNCION LPAREN LPAREN RPAREN RPAREN','arreglo',5,'p_arreglo','compilador numpy.py',216),
  ('arreglo -> FUNCION LPAREN ARREGLO RPAREN','arreglo',4,'p_arreglo','compilador numpy.py',217),
  ('arreglo -> NUMPY POINT ZEROS LPAREN NUMBERS COMA NUMBERS RPAREN','arreglo',8,'p_arreglo','compilador numpy.py',218),
  ('operacion -> VAR OPERADOR VAR','operacion',3,'p_operacion','compilador numpy.py',235),
  ('slicer -> NUMBERS DOUBLEPOINT NUMBERS','slicer',3,'p_slicer','compilador numpy.py',258),
  ('slicer -> NUMBERS DOUBLEPOINT','slicer',2,'p_slicer','compilador numpy.py',259),
  ('slicer -> DOUBLEPOINT NUMBERS','slicer',2,'p_slicer','compilador numpy.py',260),
  ('slicer -> DOUBLEPOINT','slicer',1,'p_slicer','compilador numpy.py',261),
  ('indice -> NUMBERS COMA NUMBERS','indice',3,'p_indice','compilador numpy.py',272),
  ('indice -> NUMBERS','indice',1,'p_indice','compilador numpy.py',273),
  ('indice -> NUMBERS COMA','indice',2,'p_indice','compilador numpy.py',274),
  ('indice -> COMA NUMBERS','indice',2,'p_indice','compilador numpy.py',275),
  ('indice -> slicer COMA slicer','indice',3,'p_indice','compilador numpy.py',276),
  ('indice -> slicer COMA','indice',2,'p_indice','compilador numpy.py',277),
  ('indice -> COMA slicer','indice',2,'p_indice','compilador numpy.py',278),
  ('indice -> NUMBERS COMA slicer','indice',3,'p_indice','compilador numpy.py',279),
  ('indice -> slicer COMA NUMBERS','indice',3,'p_indice','compilador numpy.py',280),
  ('indexacion -> VAR LCORCHER indice RCORCHER','indexacion',4,'p_indexacion','compilador numpy.py',290),
]
